### ISSUE TITLE
Neat but won't replace jQuery

### ISSUE THREAD

**Issue by orefalo** [vladocar/nanoJS#24]
Neat but won't replace jQuery

Checked one of my most basic projects, 

Missing 
  height() -> could use css("height") if I am careful about units
  not(),  -> ??
  scrollTop() -> element.scrollTop

Cheers,

**Comment by vladocar** [comment]
Thanks. 
Only similarity with jQuery is the syntax. nanoJS uses jQuery syntax because is logical and the syntax that everyone knows. Let say nanoJS is something between vanillaJS and jQuery.

nanoJS is not aiming to replace jQuery or to do everything jQuery does. Its library you can customise directly in the  main nanoJS.js file. It is a library that you can easily understand. So the idea is: you build your own library on top of nanoJS. nanoJS is just a starting point. I've build more the 100 small apps with the nanoJS predecessor and never used more then 10-20% of the library methods.
